//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string ImageURL { get; set; }
        public int ApplicantId { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
