//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Common> Common { get; set; }
        public virtual DbSet<ExceptionHandler> ExceptionHandler { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<NoSelection> NoSelection { get; set; }
        public virtual DbSet<PhotoCategory> PhotoCategory { get; set; }
        public virtual DbSet<Advertise> Advertise { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<DynamicPage> DynamicPage { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Paper> Paper { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Work> Work { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Applicant> Applicant { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<MainSiteBlog> Blog1 { get; set; }
        public virtual DbSet<MainSiteNews> News1 { get; set; }
        public virtual DbSet<MainSitePhotoCategory> PhotoCategory1 { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    }
}
