//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicPage
    {
        public byte Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public byte PriorityId { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<bool> IsSubPage { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
