//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotoCategory()
        {
            this.Photo = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public int ApplicantId { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string PageKeyword { get; set; }
        public string PageDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
        public virtual Applicant Applicant { get; set; }
        public virtual Information Information { get; set; }
    }
}
